### ISSUE TITLE
multiple-value tdigest.New() in single-value context

### ISSUE THREAD

**Issue by shwetapalande** [caio/go-tdigest#16]
I am trying to run the Example Usage code with the purpose of understanding how the data-structure works but it throws up `multiple-value tdigest.New() in single-value context` error.
why would this be happening?

**Comment by dgryski** [comment]
The API was updated without updating the example in the Readme

**Comment by shwetapalande** [comment]
If possible can anyone update the example then?
Thanks!

**Comment by caio** [comment]
Oops!

I've fixed the example code on 6ef48c85c5, thanks all!

@shwetapalande if things are unclear or you need more directions feel free to open more issues!
