### ISSUE TITLE
CDF returns weird values near the largest value

### ISSUE THREAD

**Issue by zeebo** [caio/go-tdigest#17]
Try adding `fmt.Println(digest.CDF(0.71875))` to the end of TestGammaDistribution. I'd expect a number between 0 and 1 (closer to 1) but i get `49999.091465195546`.

**Comment by dgryski** [comment]
Can you try other tdigest implementations?

**Comment by zeebo** [comment]
spenczar/tdigest doesn't have a CDF function. I don't know of any other go implementations...

**Comment by zeebo** [comment]
The python code appears to behave correctly on the same dataset:

```
>>> x = 0.0
>>> while x <= 1.0:
...     print(x, digest.cdf(x))
...     x += 1.0/32.0
...
0.0      4.995359053200507e-06
0.03125  0.9115930248576931
0.0625   0.9544206414358796
0.09375  0.973218153412505
0.125    0.983726287030717
0.15625  0.98986
0.1875   0.9934417744925299
0.21875  0.99564
0.25     0.9971368253995642
0.28125  0.9980973199771981
0.3125   0.9986869094283087
0.34375  0.9991296772439658
0.375    0.9993860322367275
0.40625  0.9995598178184606
0.4375   0.9997253097699493
0.46875  0.99978
0.5      0.9998281773078915
0.53125  0.99984
0.5625   0.9998774162953821
0.59375  0.9999065484867342
0.625    0.99994420404393
0.65625  0.9999772145018679
0.6875   0.999988673925574
0.71875  0.9999946871385594
0.75     1
0.78125  1
0.8125   1
0.84375  1
0.875    1
0.90625  1
0.9375   1
```

**Comment by dgryski** [comment]
Thanks. This should be pretty easy to diagnose.

**Comment by caio** [comment]
Thanks for all the details! I'm traveling now so I'll be looking at this (or a PR fixing it 😁 ) early next week

**Comment by caio** [comment]
Bored @ an airport, this was an easy fix :) Thanks a lot mates!

**Comment by zeebo** [comment]
I don't believe this is fully fixed. Here's a failing test case:

```
func TestCDF(t *testing.T) {
	td := &TDigest{
		summary: &summary{
			means:  []float64{2120.75048828125, 2260.3844299316406, 3900.490264892578, 3937.495807647705, 5390.479816436768, 10450.335285186768, 14152.897296905518, 16442.676349639893, 24303.143146514893, 56961.87361526489, 63891.24959182739, 73982.55232620239, 86477.50447463989, 110746.62556838989, 175479.7388496399, 300492.3404121399, 440452.5279121399, 515611.7700996399, 535827.0025215149, 546241.6822090149, 556965.3648262024, 569791.2124824524, 587320.6870918274, 603969.4175605774, 613751.6177558899, 624708.7593574524, 635060.0718574524, 641924.2007637024, 650656.4302558899, 660653.1714668274, 671380.9009590149, 687094.3667793274, 716595.8824043274, 740870.9800605774, 760276.2437324524, 768857.5786933899, 775021.0025215149, 787686.0337715149, 801473.4624824524, 815225.1255683899, 832358.6997871399, 852438.4751777649, 866134.2935371399, 1.10661549666214e+06, 1.1212118980293274e+06, 1.2230108433418274e+06, 1.5446490620918274e+06, 4.306712312091827e+06, 5.487582562091827e+06, 6.306383562091827e+06, 7.089308312091827e+06, 7.520797593341827e+06},
			counts: []uint32{0x1, 0x1, 0x1, 0x1, 0x1, 0x2, 0x1, 0x4, 0x5, 0x6, 0x3, 0x3, 0x4, 0x11, 0x23, 0x2f, 0x1e, 0x1b, 0x36, 0x31, 0x33, 0x4e, 0x5f, 0x61, 0x48, 0x2e, 0x26, 0x28, 0x2a, 0x31, 0x39, 0x51, 0x32, 0x2b, 0x12, 0x8, 0xb, 0xa, 0x11, 0xa, 0x11, 0x9, 0x7, 0x1, 0x1, 0x1, 0x3, 0x2, 0x1, 0x1, 0x1, 0x1},
		},
		compression: 5,
		count:       1250,
		rng:         &globalRNG{},
	}
	td.summary.rebuildFenwickTree()

	if cdf := td.CDF(7.144560976650238e+06); cdf > 1 {
		t.Fatalf("invalid: %v", cdf)
	}
}
```

that fails with

```
=== RUN   TestCDF
--- FAIL: TestCDF (0.00s)
	tdigest_test.go:34: invalid: 624.3678441026399
```

Sorry about the size. I pulled it from a production value I found failing.

**Comment by zeebo** [comment]
I believe the problem lies in [this line](https://github.com/caio/go-tdigest/blob/master/tdigest.go#L288).

It looks like the expression is attempting to compute the number of "observations" accounted for by interpolating inside of the centroid. I'd expect to have it divide by the observed count (like [above](https://github.com/caio/go-tdigest/blob/master/tdigest.go#L271)) but is instead just dividing by two. If I change it to divide by the count, then I get a value like `0.9989885505642238` which is where I'd expect it.

I'll send a pull request shortly in case you agree with my analysis.

**Comment by caio** [comment]
You're absolutely right, nice catch! When you submit the PR I'll make some
time to merge it and release the proper fix. That should teach me to
actually write real tests when claiming I fixed something :x

And no need to apologise for the test size, it's super useful!!

Thanks a lot

**Comment by caio** [comment]
Oh, you did it already 🎉 I'll sit down in front of the computer tomorrow morning and get this published
